#!/bin/bash

mysqld_safe &

mysql_ready() {
	mysqladmin ping --socket=/run/mysqld/mysqld.sock --user=root --password=ctfshow > /dev/null 2>&1
}

while !(mysql_ready)
do
	echo "waiting for mysql ..."
	sleep 3
done

service apache2 start

source /flag.sh

rm -rf /flag.sh

tail -F /dev/null
