#!/bin/sh

mysqld_safe &

mysql_ready() {
	mysqladmin ping --socket=/run/mysqld/mysqld.sock --user=root --password=ctfshow > /dev/null 2>&1
}

while !(mysql_ready)
do
	echo "waiting for mysql ..."
	sleep 3
done

/bin/bash -c 'source /flag.sh'

echo "docker-php-entrypoint"

tail -F /dev/null
